---
title: "Mixed-effect model NF"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(metafor)
library(meta)
library(ggplot2)
library(janitor)    # Adding this package in
library(tidyverse)
library(dplyr)
library(sjPlot)
```
```{r}
getwd()
```
## Running moderator analysis
```{r}
read.csv("ModeratorsNF.csv", header = TRUE)
```
```{r}
SMR<-ModeratorsNF$`Soil moisture regime`
SMR
PLU<-ModeratorsNF$`Previous land use/disturbance`
PLU
Precipitation<-ModeratorsNF$Precipitation
Precipitation
accession<-ModeratorsNF$accession
accession
WT<-ModeratorsNF$Wood_Type
WT
Genus_NFP<-ModeratorsNF$Genus_NFP
Genus_NFP
Age<-ModeratorsNF$Age
Age
```
## Effect size computation
```{r}
rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, data = ModeratorsNF)
```
# Precipitation meta-regression
```{r}
rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, mods = ~Precipitation, data = ModeratorsNF)
```
```{r}
tiff("PrecipitationRegressionNF", units="in", width=20, height=10, res=300)
plot(ModeratorsNF$LRR~Precipitation, data=MyData_NPK_, xlab="Precipitation (mm/yr)", ylab="Net treatment effect on plantations biomass")
points(Precipitation, fitted(rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, mods = ~Precipitation, data = ModeratorsNF)), pch="x", col="red")
abline(coefficients(rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, mods = ~Precipitation, data = ModeratorsNF)))+
  theme(axis.title.x = element_text(size = 20))+
  theme(axis.title.y = element_text(size = 20))
         
```

## Categorical moderators analysis
#Soil moisture regime
```{r}
rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, mods = ~SMR-1, data = ModeratorsNF)
#We can see that the soil moisture regime does not have an influence of the effect of the treatment. 
```

## Previous land use
```{r}
rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, mods = ~PLU-1, data = ModeratorsNF)
#Previous land use/disturbance does influence the net-effect of intercropping N-fixing plants on plant biomass. Effect size differ among the types of previous land use
# When N-fixing plants were intercropped in plantations that were grown on previously  cropped land or w the effect of the treatment (the change in biomass) was postivie : when N-fixing crops were interplanted in previous crooped land, it increases the biomass of the main crop by 40%.
```
# Genus
```{r}
rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, mods = ~Genus-1, data = ModeratorsNF)
#Genus does not  have a significant influence  on the effect of intercropping N-Fixing plants treatment. 
```
## Wood type
```{r}
rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, mods = ~WT-1, data = ModeratorsNF)
#when N-fixing crops where intercropped in coniferous stand, it decreases the biomass of the main tree crop by a slight margin (12%), although it was not statistically significant. Conversely, when hardwoods were mixed with N-fixing crops, it boosted their productivity and abovegrounf biomass by about 4%, although it was not statistically statiscally significant as well. 
```
## Genus of intercropped plant
```{r}
rma.mv(ModeratorsNF$LRR, ModeratorsNF$LRR_var,random = ~1|accession, mods = ~Genus_NFP-1, data = ModeratorsNF)
```

## Figure 1 Manuscript
```{r}
read.csv("NFforestmoderators.csv", header = TRUE)
```

```{r}
overall_effect<-NFforestmoderators$estimate_exp
overall_effect
Moderator<-NFforestmoderators$Moderator
Moderator
lower<-NFforestmoderators$lower
upper<-NFforestmoderators$upper
```
```{r}
NFforestmoderators$Group<-factor(NFforestmoderators$Group, levels = c("Overall effect", "Soil moisture regime", "Previous land use","Tree genus","Intercropped plant genus","Wood type"))
```

```{r}
# Draw the plot with 95% confidence interval using ggplot2
tiff("NFModeratorEffect", units="in", width=15, height=15, res=300)
ggplot(NFforestmoderators)+geom_pointrange(aes(x=overall_effect, y = Moderator, 
                      xmin = lower, 
                      xmax = upper))+
  geom_vline(aes(xintercept = 0), linetype = 2, colour = "red") + 
  facet_wrap(facets = ~NFforestmoderators$Group, 
             ncol = 1, 
             strip.position = 'right', 
             scales = "free_y")+
  scale_x_continuous(name="Per cent change in tree aboveground carbon stocks from interplanting N-fixing plants", limits=c(-70, 140), breaks = c(-80,-60,-40,-20,0,20,40,60,80,100,120,140))+
  theme(axis.title.x = element_text(face = -10))+
  scale_y_discrete(name="")+
  theme(legend.position = "none",
        strip.background =element_rect(colour = "white",
                                       fill = "forest green"))+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),text = element_text(size=25))+
  theme(panel.background = element_blank())+
  theme(panel.border = element_rect(colour = "gray", fill = NA))+
theme(strip.text.y.right=element_text(angle = 0))+
theme(strip.text.y.right=element_text(size = 25))
dev.off()
```


##Regression with Stand Age (Figure 2)
```{r}
# Load in data
AgeRegressionNFtest <- read_csv("AgeRegressionNFtest.csv") %>%   
  clean_names()
```

```{r}
mdl_nf <- rma.mv(AgeRegressionNFtest$lrr, 
                 AgeRegressionNFtest$lrr_var, 
                 random = ~1|accession, 
                 mods = ~AgeRegressionNFtest$age, 
                 data = AgeRegressionNFtest)

# Save the coefficients and coefficient standard errors to objects

coefs <- coefficients(mdl_nf)
ses <- mdl_nf$se

fitLine <- data.frame(x = 1:max(AgeRegressionNFtest$age),
                      y = coefs[1] + coefs[2]*1:max(AgeRegressionNFtest$age),
                      yLow = (coefs[1]-1.96*ses[1]) + (coefs[2]-1.96*ses[2])*1:max(AgeRegressionNFtest$age),
                      yHigh = (coefs[1]+1.96*ses[1]) + (coefs[2]+1.96*ses[2])*1:max(AgeRegressionNFtest$age))

# Draw the plot with 95% confidence interval using ggplot2

p_nf <- ggplot(data = AgeRegressionNFtest) +
  geom_point(aes(x = age, y = lrr)) +
  xlab("Stand age (years)") +
  ylab("ln(RR) of change in AGC stocks") +
  geom_ribbon(data = fitLine, aes(x = x, ymin = yLow, ymax = yHigh), fill = "blue", alpha = 0.2) +  # Add the 95% Confidence Interval using geom_ribbon
  geom_line(data = fitLine, aes(x = x, y = y), col = "black") +
  geom_hline(aes(yintercept = 0), linetype = 2, colour = "red")+
  scale_x_continuous(breaks = c(0,2,4,6,8,10,12,14))+
# Add the best fit line
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())   # Remove grid from panel (up to you if you want to keep)
  
p_nf

# Save as .jpeg

ggsave("AgeRegressionNFLimit15.jpg", p_nf, device = "jpeg", height = 6, width = 8.5)
```





